### ISSUE TITLE
REST interface for creating battle

### ISSUE THREAD

**Issue by sugarfree1** [StevenWeathers/thunderdome-planning-poker#48]
Hi there, thanks for the great tool

I think it would be much easier to create battles by REST. For example, I have list of tasks in my bugtracker and I want to add all of them to battle.

It would be great to send
```
POST /battles
```
and get JSON response
```
{battle_id: "hash"}
```
and then send
```
POST /battles/:battle_id/tasks
```
with data
```
[
  {name: "task_name1"},
  {name: "task_name2"}
]
```

Another great option would be:
```
GET /battles/:battle_id/tasks
```
and get response
```
[
  {name: "task_name1", estimates: [1, 3, 3], winning_estimate: 3},
  ..
]
```

**Comment by StevenWeathers** [comment]
Thanks for the feedback,

An external facing API is something I've thought about doing since I started building Thunderdome.  While I don't know when I will get to this feature, I will also look at tweaking the UI to be able to add plans in bulk to the battle during the create step.  This is something else I started to think about recently.

**Comment by StevenWeathers** [comment]
While not an external facing API yet, I did go ahead and throw together the first iteration of adding plans to battle during create.  See #49

**Comment by StevenWeathers** [comment]
Closing this until an external api milestone is something I'm ready to implement.
