### ISSUE TITLE
Import XML "select file" button is not opening the file browser

### ISSUE THREAD

**Issue by rdelcorro** [StevenWeathers/thunderdome-planning-poker#499]
When trying to import plans from jira xml or CSV, the select file button is not opening a file browser. 

Tested on version 3.6.3 in chrome on mac

**Comment by StevenWeathers** [comment]
Those buttons are currently working for me, check your browser permissions to make sure you're able to access local files.

**Comment by scottux** [comment]
Have you tried the steps outlined here? https://support.google.com/chrome/thread/134852610/since-latest-mac-os-can-no-longer-upload-any-files-in-chrome?hl=en

I can confirm these buttons work for me.

Which version of OSX are you running? Does your company have any security policies in place that would prevent file uploads?

**Comment by rdelcorro** [comment]
It started working again after In upgraded chrome. Sorry for the false positive. Since this started after an upgrade from 2 to 3 I thought it was related
